name: Clippy Checks

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
  schedule:
    - cron: "29 20 * * 0"

jobs:
  rust-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: macos-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    strategy:
      matrix:
        target:
          - name: aarch64-apple-darwin
            feature: ["web", "server"]
          - name: x86_64-apple-darwin
            feature: ["web", "server"]
          - name: aarch64-unknown-linux-gnu
            feature: ["web", "server"]
          - name: x86_64-unknown-linux-gnu
            feature: ["web", "server"]
          - name: x86_64-pc-windows-gnu
            feature: ["web", "server"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          os: macos-latest
          target: ${{matrix.target.name}}
          token: "${{ github.token }}"
          cargo_bins: wasm-bindgen-cli clippy-sarif sarif-fmt

      - name: Run rust-clippy
        run: cargo clippy
          --features ${{matrix.target.feature}}
          --message-format=json | clippy-sarif | tee rust-clippy-${{matrix.target.feature}}.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rust-clippy-${{matrix.target.feature}}.sarif
          wait-for-processing: true
